[package]
name = "rurel-test"
version = "0.1.0"
authors = ["CKIRUser"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rurel = "0.1.2"
